### PR TITLE
Fix for setting left style checkRight.js

### PR DESCRIPTION
**Pull request by jondavidchristopher**
The tooltip floats off screen on the right side do to missing style method.

### CODE REVIEW

**Comment by afshinm** [comment]
thanks @jondavidchristopher. Do you have any examples of how this change is going to affect the tooltip styling? perhaps a jsfiddle, codesandbox, etc.

**Comment by markgonz** [comment]
I am having the same issue and posted it here: https://github.com/usablica/intro.js/issues/1169. I made the edits mentioned above by jondavidchristopher and this did resolve the issue of tooltips going off the right side of the screen. However, it did not fix the position of the arrow for tooltips that were going of screen before. Screen shots below for before and after applying the fix. Please note the after screenshot where the tip is now onscreen, but the arrow is still not in the correct location.

**Before fix:**
Screen Shot 2021-02-16 at 11 19 22 AM

**After fix:**
Screen Shot 2021-02-16 at 11 15 16 AM

.

**Comment by cactusjosh** [comment]
Can we merge this please? Looks awesome!

**Comment by markgonz** [comment]
Any chance this will me merged soon?

**Comment by Adriiad** [comment]
+1 here. Did the same thing and it fixed my problem.

**Comment by markgonz** [comment]
Any word on plans to merge this PR?

**Pull request merged**
