### PR TITLE
start intro for group of elements

### PR DESCRIPTION
**Pull request by Delysid**
`data-intro-group` option of element specifies intro group, which you can launch by `introJs.start(group_name)`

### CODE REVIEW

**Comment by piotr-cz** [comment]
Seems that this feature is not present in the v2 anymore

**Comment by afshinm** [comment]
@piotr-cz will have a look

**Comment by piotr-cz** [comment]
Sorry, this feature has never been merged (see [v1.1.1](https://github.com/usablica/intro.js/blob/v1.1.1/intro.js)).

I'm planning to work around it:

1. I store intro text in in other, group data attribute (`data-intro-namespace="menuitem", data-intro-menuitem="Click here for fireworks"`)
2. _before_ introJs Start copy it's contents to data-intro attribute
3. _after_ introJs end remove data-intro attributes

**Comment by tnchuntic** [comment]
is this implemented already? I couldn't make it work on my end.

**Comment by afshinm** [comment]
@bozdoz what do you think? I believe it should be easy to rebase / reimplement.

**Comment by bozdoz** [comment]
Agreed. I can take a look at this shortly.

**Comment by xmflswood** [comment]
+1

**Comment by dspoonia7** [comment]
+1

**Pull request merged**
