### PR TITLE
Enter key will now progress to next page for multi-page intro

### PR DESCRIPTION
**Pull request by ericenns**
Addresses issue #445

### CODE REVIEW

**Comment by afshinm** [comment]
I think we should modify multipage example because this behavior is correct for single page intros, right?

**Comment by ericenns** [comment]
Yes so basically before, enter key would progress to next step until it hit the last where it would end the tour. In a single page tour it will still just end the tour as normal.

**Comment by afshinm** [comment]
Right, so let's change the multi-page example instead of the JS code. Can you help me? :)

**Comment by ericenns** [comment]
fixed in 6fd0378313c5b55c737361d9c704ec081d5b65f9

**Comment by afshinm** [comment]
Thank you @ericenns

**Pull request closed without merging**
