### PR TITLE
Add callbacks for close intro on overlay layer click and esc

### PR DESCRIPTION
**Pull request by Rxbsxn**
I have added some quite important callbacks when we want to handle different actions in different intro close case.

### CODE REVIEW

**Comment by bozdoz** [comment]
I'm not sure of a use case for this. In any case, it could work.  I might prefer something more generic; something event-based, instead of callback-based, like:

```javascript
intro.on('exit', function () {
  console.log('something fired exit');
});
```

where the code in Intro.js is replaced with something like:

```javascript
this.fire('exit');
```

**Comment by Rxbsxn** [comment]
@bozdoz Could you explain your approach a little more because you use callbacks everywhere in code?

**Comment by bozdoz** [comment]
> "explain your approach"

The callback style of development requires (1) checking for a function after an event, then (2) executing it.  An event-based approach would only require firing an event, where the event handling deals with executing **any number** of functions (note that the callback approach would only execute one).  Also, the way this is currently implemented, there's also this strange idea of creating a callback function with a method:

```javascript 
onclick: function (cb) {
  this._onclick = cb;
} 
```

But, this could easily be done directly like this:

```javacript
intro._onclick = function () {};
```

All I'm saying is that this library ought to be cleaned up a bit.  **I have no objection to your Pull Request**.  I have only hesitation, because I think the library ought to be optimized.  For what it's worth, I added a recommendation to move towards event-based logic in #602.

**Comment by dcantatore** [comment]
@afshinm - Are any of the pull requests going to be merged in?

**Pull request closed without merging**
