### PR TITLE
Fix issue 356 - no interaction with the target element.

### PR DESCRIPTION
**Pull request by yuvale**
An attempt to fix issue #356.
See the commit message for details.

### CODE REVIEW

**Comment by bgruening** [comment]
This looks also good to me.

**Comment by afshinm** [comment]
I will merge this one for the next version. Thank you @yuvale

**Comment by radhe-saini** [comment]
please send some example code snipped

**Comment by architgarg** [comment]
It doesn't seem to be working.

Using: 

```
    "intro.js": "^7.0.1",
    "intro.js-react": "^1.0.0",
```

**Comment by M-r-hydra** [comment]
isnt Working :/

**Comment by baki-kucukcakiroglu** [comment]
Guys, I tried a solution given under another issue and it worked. 

Please check this[ comment! ](https://github.com/usablica/intro.js/issues/1202#issuecomment-1647264044)

**Pull request merged**
