### PR TITLE
Update intro.js

### PR DESCRIPTION
**Pull request by ustmaestro**
CHANGE LOG
1. add tooltip distance option - distance betwen highlight and tooltip in case these is needed or for other purposes
2. add elements padding option - hihglight and tooltip padding if more padding is needed
3. add highlight style option - default, square, circle (highlight in diferrent styles: circle around element, square around element or default)
4. add data-style attribute - for inline highlight style option
5. add posibility of change the steps number container (highlight or tooltip) - where step number will be shown on highlight or tooltip
6. better tooltip positions (more futures) - top, top-middle, top-right, 
                                                           right, right-middle, right-bottom, 
                                                           bottom, bootom-middle, bottom-right
                                                           left, left-middle, left-right
   
   There was only: top, right, bottom and left
   Now we cover all posible positions
7. changed tooltip referance from element to highlight - place tooltip around highlight not around highlighted element
   
   In case of circle, square or if we setup padding - we need that
8. add onbeforestart callback - callback before plugin start in case you need to do stufs before the plugin starts

TODO: improve auto position

### CODE REVIEW

**Comment by afshinm** [comment]
Thank you for this nice PR but it's a little complicated to merge. Please submit different PRs for each feature so I can merge it better.

**Comment by bgruening** [comment]
@ustmaestro awesome! Can you either split this into smaller chunks or rebase this PR so that @afshinm can merge it? We need this in! :)

**Comment by ustmaestro** [comment]
@afshinm, @bgruening HI! I used this plugin in one of my application 4 months ago and I need some more features. Basically was to improve positions and different styles for highlight. Now I'm working on another project, so I do not have free time to do separate PR's and remember what was do 4 months ago. There is many changes that I have done and now I do not remember these changes.

I added a folder called new in my fork that is show the basic usage of what I did.
If someone is ready to check and do separate PR's or @afshinm have time to add these features individually to main repo will be nice.

**Comment by ustmaestro** [comment]
If I will find a window in my working program, I will try to these PR myself

**Pull request closed without merging**
