### PR TITLE
clarify license, wording and SPDX

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
The MIT license is not viral copyleft as the current wording seems to imply. Either update the wording as in this PR or switch to AGPL 3+.

**Comment by graingert** [comment]
@afshinm ping

**Comment by niftylettuce** [comment]
Here's an MIT licensed version, free for all.  https://github.com/niftylettuce/introjsmit  Install on Bower or NPM with the name `intro.js-mit`

**Comment by graingert** [comment]
@afshinm ping ping ping

**Comment by afshinm** [comment]
I will update this for the next version. Thanks for reminding @graingert

**Pull request closed without merging**
