### PR TITLE
Re-added PR #80 for groups

### PR DESCRIPTION
**Pull request by bozdoz**
I omitted changes to css and minified files, and added an example.

### CODE REVIEW

**Comment by afshinm** [comment]
Hmm, nice. The thing is, we can already pass a parent element and start the intro for a specific container rather than document.body.

Do you think these two have conflict with each other?

**Comment by bozdoz** [comment]
I think it would find the group matches within the selected element, wouldn't it? Don't think it would conflict.

**Comment by afshinm** [comment]
Do you think this PR can address an issue like this: https://stackoverflow.com/questions/46679734/intro-js-how-to-select-multiple-element-navigate-between-pages-with-continuous ?

**Comment by bozdoz** [comment]
That's quite an involved StackOverflow question, so I am not sure.  My best guess use-case is to run one introjs after another, like in the example I posted with it: one iterated even numbered sections and the other iterated the odd, and there was a button for each.

**Pull request merged**
