### PR TITLE
Try to fix methods being called on `null`

### LINKED ISSUE #638: prevTooltipButton/nextTooltipButton is sometimes null
Encountering errors like

```
Unable to get property 'removeAttribute' of undefined or null reference
```

at https://github.com/usablica/intro.js/blob/v2.3.0/intro.js#L1012

or 

```
Unable to get property 'tabIndex' of undefined or null reference
```

at https://github.com/usablica/intro.js/blob/v2.3.0/intro.js#L856

Is it missing some null checking?

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #638 
Has been using https://github.com/PikachuEXE/intro.js/tree/fix/null-reference for months (which is based in 2.3.0)

### CODE REVIEW

**Comment by afshinm** [comment]
thanks for this fix. I will test it locally and then merge

**Comment by Adam13531** [comment]
@afshinm hey, is there an ETA on incorporating this fix? I tested it out in my own codebase and it enabled creating tutorials with a single step (which previously wasn't working).

P.S. great work both of you. :)

**Comment by afshinm** [comment]
thank you both @PikachuEXE @Adam13531 

I will review this locally and apply your patch @Adam13531!

**Comment by afshinm** [comment]
done!

**Comment by Adam13531** [comment]
@afshinm hey, thanks for merging in the request! The only thing I wanted to point out is that the added conditions are redundant:

```js
typeof nextTooltipButton !== "undefined" && nextTooltipButton != null
```

could just be 

```js
nextTooltipButton != null
```

**Comment by PikachuEXE** [comment]
I think I meant to use 
```js
typeof nextTooltipButton !== "undefined" && nextTooltipButton !== null`
```
But
```js
nextTooltipButton != null
```
also works too.

**Pull request merged**
