### PR TITLE
Fix build process

### PR DESCRIPTION
**Pull request by mdanzinger**
I noticed there were some build errors when attempting to build some changes I made, so I figured I'd send 'em your way.

### CODE REVIEW

**Comment by afshinm** [comment]
I don't have this problem. Could you please let me know what is your components version?

**Comment by mdanzinger** [comment]
I'm using the latest version of node-minify(2.0.2), obtained by running `npm install`. 

```cd BUILD && node BUILD.js
node-minify deprecated Instantiate is no longer necessary.
new compressor.minify() is deprecated.
Please use:

  var compressor = require("node-minify");
  compressor.minify();

 ../node_modules/node-minify/lib/node-minify.js:30:3
node-minify deprecated type was renamed to compressor ../node_modules/node-minify/lib/node-minify.js:30:3
node-minify deprecated fileIn was renamed to input ../node_modules/node-minify/lib/node-minify.js:30:3
node-minify deprecated fileOut was renamed to output ../node_modules/node-minify/lib/node-minify.js:30:3
/Users/mendy31/dev/intro.js/node_modules/node-minify/lib/setup.js:201
    throw new Error(setting + ' is mandatory.');
    ^

Error: compressor is mandatory.
    at mandatory (/Users/mendy31/dev/intro.js/node_modules/node-minify/lib/setup.js:201:11)
    at /Users/mendy31/dev/intro.js/node_modules/node-minify/lib/setup.js:188:5
    at Array.forEach (native)
    at checkMandatories (/Users/mendy31/dev/intro.js/node_modules/node-minify/lib/setup.js:187:5)
    at setup (/Users/mendy31/dev/intro.js/node_modules/node-minify/lib/setup.js:43:3)
    at new minify (/Users/mendy31/dev/intro.js/node_modules/node-minify/lib/node-minify.js:31:14)
    at Object.<anonymous> (/Users/mendy31/dev/intro.js/BUILD/BUILD.js:6:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
make: *** [build] Error 1```

**Comment by afshinm** [comment]
cool thanks, I will have a look 👍

**Comment by mdanzinger** [comment]
No problem! Let me know if you'd like any more information about my environment.

**Comment by afshinm** [comment]
already fixed. thanks @mdanzinger

**Pull request closed without merging**
