### PR TITLE
Fix documentation error

### PR DESCRIPTION
**Pull request by zanderle**
There was an error in the documentation

### CODE REVIEW

**Comment by zanderle** [comment]
I see. It might be useful to put that in the documentation then?

**Comment by bozdoz** [comment]
Does not seem to apply to the current state of the repo.

**Comment by zanderle** [comment]
Ok, I can close then. After all the PR is 3 years old...

**Comment by bozdoz** [comment]
Thanks, @zanderle, and I do realize how untimely this is.  I just became a regular contributor a month or so ago, and am trying to clean things up.  :smiley:

**Pull request closed without merging**
