### PR TITLE
Dart wrapper

### PR DESCRIPTION
**Pull request by moomoohk**
intro.js wrapper for [Dart](http://dartlang.org)

### CODE REVIEW

**Comment by olmec-akeru** [comment]
So it seems that this project is dead... shall we create a separate fork?  Looks like the root of introjs has been abandoned by usabilca.

**Comment by afshinm** [comment]
this is really interesting, thanks for this but I think it'd be better if we keep this as a separate branch/repo and then refer to the repo in the Introjs readme?

**Comment by afshinm** [comment]
btw, how can I test it? sorry haven't used Dart

**Comment by moomoohk** [comment]
Hey :)
I already have a repo open and I don't mind maintaining it. The wrapper doesn't contain much code as you can see.

I'm not sure what kind of tests you want to run but I've added the `example/dart` folder where I used to wrapper to run 1:1 the original JS examples. If you open their HTML files in your browser you should see the example run just like before except it's Dart behind the scenes and not JS.

**Comment by moomoohk** [comment]
Hey @afshinm, any news?

**Comment by afshinm** [comment]
sorry for the delay @moomoohk. I'm closing this now but I'm going to add the link to your repository now.

**Comment by moomoohk** [comment]
Awesome :)

I'll try to keep it up to date

**Pull request closed without merging**
