### PR TITLE
Show hints

### LINKED ISSUE #616: Hiding all hints and then displaying them again
Hello, seems like hints don't work this way. For example I've got one button, which is "Show/Hide Hints". When hints aren't displayed, I call "introJs().addHints()" and it displays all hints. On the second click, I call "introJs().hideHints()", which removes all hints and after this I have a problem. When I click that button third time "introJs().onhitsadded()" is getting called, but no hints are shown.

### PR DESCRIPTION
**Pull request by nblackburn**
Fixes #616.

### CODE REVIEW

**Comment by Narretz** [comment]
@afshinm Would be cool if this could be merged. (the wiki needs to be updated, though).

**Comment by nblackburn** [comment]
@Narretz Can't do that until this is merged.

**Comment by afshinm** [comment]
Nice one! thanks for this

**Comment by nblackburn** [comment]
Updated wiki

**Pull request merged**
