### PR TITLE
Condition attribute for steps and edited redundant loop

### PR DESCRIPTION
**Pull request by stijn1989**
I use intro.js when users push the 'help' button on the page. But the page is sometimes displayed on smartphones, tablets or computers. So some steps aren't needed to be displayed because other elements are hidden on small devices.

That's why I've build condition in steps. You can do it in JSON or attribute "data-condition". I've included an example for each of them.

Next I've read the TODO in the method "_introForElement". So I've decided to give it a try. The loop is easy. It loops through all the data-intro elements. The ones with data-step are kept in place but the ones without data-step are placed when there is space or replaced if an other data-step needs to be there.
There is an array that keep track which steps are occupied and which are occupied to but can't switch place.

### CODE REVIEW

**Comment by afshinm** [comment]
This is very interesting. I was thinking about adding the same concept using https://github.com/usablica/parserjs. My only concern is that `return new Function()` might have some security issue because this can evaluate any function, e.g. alert()

**Comment by stijn1989** [comment]
Yes I've read that eval() is very risky with security and then I found this "new Function" workaround. But if the condition doesn't come from 3rd party sources, why should you worry about it? The JSON or attributes are static programmed.

**Comment by afshinm** [comment]
What do you think @bozdoz

**Comment by bozdoz** [comment]
Looks better suited for the programmatic method, using onbeforechange, or something like that.  I think JavaScript should be in JavaScript, not HTML, generally.  I don't really understand why you'd want to add it within HTML; but maybe I'm not the right person to evaluate this.  I suppose it could help some editor of a WordPress blog, or some other content-editor, where the user only has access to HTML.  That's the best use-case I can think of.  I am also unsure of the risk involved; I agree that if they're static, why worry.  Though I have heard, of course that eval is evil.

**Pull request closed without merging**
