### PR TITLE
Added buttonClass to options

### PR DESCRIPTION
**Pull request by cdownie**
buttonClass value is initially set to the default value 'introjs-button'. Consumers now have the option to set their own class for all buttons used during the tour.

### CODE REVIEW

**Comment by afshinm** [comment]
hey @cdownie, thanks!

I think you can use `tooltipClass` to add the class name and select the buttons using CSS selectors. Let me know what you think.

**Comment by cdownie** [comment]
I think you could do that as well. 

In our case, it seemed simpler to add our existing button classes vs adding/editing new styles specifically for introjs. We essentially were able to add 'stock bootstrap' classes on the component and everything fell in line with our theme at that point.

**Comment by bozdoz** [comment]
I like the idea of adding class names, but I don't like the idea of changing class names (because the introjs css would break); I just can't see it being used by many people.

But this, maybe:

```javascript
skipTooltipButton.className = 'introjs-button introjs-skipbutton';
if (this._options.btn_class) {
  _addClass(skipTooltipButton, this._options.btn_class);
}
```

Still awkward.  Maybe there's a better way to offer this level of customization without options.  For example, if we're thinking about making introjs extensible, #602, we could have a method for creating a button:

```javascript
IntroJS = {
  Button : function (html) {
    var btn = document.createElement('a');
    btn.setAttribute('role', 'button');
    btn.tabIndex = 0;
    btn.innerHTML = html;
    // use IntroJS utility functions to manipulate element
    IntroJS.utils.addClass(btn, 'introjs-button');
    this.container = btn;
  }
}
```

And then developers could overwrite the button creation method like this (this is an **extremely** simplified example):

```javascript
// save old function
IntroJS.originalButton = IntroJS.Button;
// overwrite
IntroJS.Button = function (html) {
  // call parent function
  IntroJS.originalButton.call(this, html);
  IntroJS.utils.addClass(btn, 'btn-primary btn-lg');
};
```

Ideally we'd have a whole system where developers can easily and actually extend functions (rather than overwrite them).  It might be helpful, but it also might be excessive.  Just an idea. :D

**Comment by cdownie** [comment]
The intention in this case was indeed to overwrite, replace, and 'break' the existing styles. Without removing the existing introjs-button style, further work would have needed to be done to remove and reset the existing styles added by the stock class.

With this method I am able to apply multiple classes to a button (ie 'btn btn-link btn-sm') and achieve the desired look without modifying existing styles. If a user wished, they could include introjs-button in their list of buttonOptions and keep the existing styles

styledbuttons

**Comment by bozdoz** [comment]
Interesting. Thanks for the use case and example!  I can see how this would be useful, but, again, it would be great to be able to get to a position where the entire library is more flexible, more modular, yet still widely use-able with default settings.  This will be a good example to keep in mind.

**Pull request merged**
