### PR TITLE
cleaner removing of empties in introItems array

### PR DESCRIPTION
**Pull request by SirenHound**
Feedback welcome.

### CODE REVIEW

**Comment by vivek12345** [comment]
This looks good to me.I like it.Just one question, will this filter function work on all browsers being supported by intro at the moment?

**Comment by SirenHound** [comment]
Good point, I keep forgetting about browser compatibility. I don't know what versions of browsers IntroJs is supporting but it should work on all major current browsers.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by bozdoz** [comment]
Would be a good idea for the project to explicitly list which browsers and versions the project supports.  Maybe even write a test to ensure it.

@afshinm

**Comment by bozdoz** [comment]
Also, this PR should work for IE9+

**Comment by afshinm** [comment]
That's a great idea @bozdoz. A test would be perfect to show the browser compatibility.

I'd prefer not to add something like `Array.filter()` for now. Let's do that test and then merge this.

Looks like `filter` works for IE9+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Pull request closed without merging**
