### PR TITLE
Add new function `goToStepNumber`

### PR DESCRIPTION
**Pull request by doits**
refs #299

### CODE REVIEW

**Comment by afshinm** [comment]
cool thanks I will have a look

**Comment by afshinm** [comment]
Sorry @nblackburn, which part of the PR?

**Comment by nblackburn** [comment]
@afshinm Line 318

**Comment by afshinm** [comment]
Ok, what is the difference between this and this one: 

```
    goToStep: function(step) {
      _goToStep.call(this, step);
      return this;
    },
```
https://github.com/usablica/intro.js/blob/master/intro.js#L1765

**Comment by doits** [comment]
> Ok, what is the difference between this and this one: [...]

Not sure what you mean exactly, you mean the difference? See the commit msg:

> This allows to go to a specific step with the specific `data-step`
> attribute. This differs from `goToStep` in the way that `data-step`
> does not have be continuous to pick the desired element.
> 
> For example:
> 
> ```
> <div id="first" data-step='5'></div>
> <div id="second" data-step='9'></div>
> 
> // to get #second one can do now:
> introJs().goToStepNumber(9); --> #second
> 
> // or with goToStep:
> introJs().goToStep(2); --> #second
> ```

**Comment by afshinm** [comment]
ah yeah right. sorry I didn't read it carefully (or I need to change my glasses).

Thanks for this, could you please update the docs as well so I can merge it today?

**Comment by doits** [comment]
Added it, you have to correct `Available since` in ready though.

**Comment by afshinm** [comment]
Perfect! thanks @doits 

thanks for review @nblackburn

**Pull request merged**
