### PR TITLE
api to programatically show hint dialog

### PR DESCRIPTION
**Pull request by Simon-Briggs**
Hi, 

I wanted to be able to programatically open up the hint dialog, so slightly modified the _hintClick method to make it easier to call from elsewhere.

### CODE REVIEW

**Comment by stijn1989** [comment]
Aren't hints supposed to be clicked? If you need to show a step, can't you use the start() method?

**Comment by Simon-Briggs** [comment]
I've been using the start method for a brief overview of the page, then hints afterwards to help users along. But I found that just a hint icon wasn't obvious enough, especially for the first one, so wanted to show them automatically.

**Comment by afshinm** [comment]
This is a good idea, I like it. I'm going to test it locally and then merge it for the next version. 

Thanks!

**Comment by afshinm** [comment]
merged.

**Pull request closed without merging**
