### PR TITLE
#791

### PR DESCRIPTION
**Pull request by SamanthaAdrichem**
* Added await syntax to all callbacks

This is how the code has been implemented in our system, allowing us to open modals and wait until they are done loading.
I'm currently loading our fork. But would be nice if you guys could test it further and eventually create it as a version.

```
this.introJs.onbeforechange(async () => await this.stepChange());


public async stepChange(): Promise<void> {
	const currentStepIndex: number = this.introJs._currentStep;

	if (this.currentStepIndex && 'function' === typeof this.steps[this.currentStepIndex]?.onLeave) {
		await this.steps[this.currentStepIndex]?.onLeave();
	}

	if (!this.steps[currentStepIndex]) {
		return;
	}

	if ('function' === typeof this.steps[currentStepIndex]?.onEnter) {
		await this.steps[currentStepIndex]?.onEnter();
	}

	this.currentStepIndex = currentStepIndex;
}

onEnter: () => {
	return new Promise((resolve: () => void) => {
		const subscription: Subscription = this.campaignModalService.bsModalService.onShown
			.subscribe(() => {
				resolve();
				subscription.unsubscribe();
			});
		this.campaignModalService.show(TourComponent.TOUR_CAMPAIGN_ID);
	});
}
```

### CODE REVIEW

**Comment by afshinm** [comment]
Hey @SamanthaAdrichem, thanks for sending this patch. I'm not sure if it's a good idea to add the async/await to the callbacks yet as I'm not sure about the side-effects.

Am I right in saying that you need the async behavior because you need to pull any config/data from your server?

**Comment by SamanthaAdrichem** [comment]
In theory it should not break anything i tested the following in the browser first (please note im re-typing this on my phone, so sorry for typos)

```
function test() {
    console.log(‘test called’);
}

async function testAsync() {
    await test();
    console.log(‘async waited’);
}

testAsync();
```

and that didnt fail. So if it doesnt return anything or a promise it should still work.


But i think it is wise to test it more thorougly.

i dont need it for an api call, i need it to wait until a modal has openend and the angular view has rendered.

**Comment by afshinm** [comment]
Sorry for the delay on this. After reviewing this change, I think merging this PR doesn't improve anything mainly because non of Intro.js callbacks are async (i.e there is no async function in our callbacks). Thanks for bringing this up and your contribution.

**Comment by afshinm** [comment]
Hey @SamanthaAdrichem, reviewing this PR again, I believe it shouldn't have any side-effects since `await` is sort of noop when used on a non-async function. My apologies. I'm going to work on a PR separately to add this. Thank you for bringing this up!

**Comment by afshinm** [comment]
PR https://github.com/usablica/intro.js/pull/1712

**Pull request closed without merging**
