### PR TITLE
Fix some stuff in the demo

### PR DESCRIPTION
**Pull request by jack126guy**

### CODE REVIEW

**Comment by jack126guy** [comment]
Typo fixed in #550 but the duplicate step 4 is still there.

**Comment by afshinm** [comment]
Hello there, sorry about that. Could you please rebase this with upstream? so I can merge it.

**Comment by jack126guy** [comment]
Done.

**Comment by jack126guy** [comment]
@afshinm Uh...any reason why this isn't being merged?

**Pull request closed without merging**
