### PR TITLE
Removed unnecessary semi-colons

### PR DESCRIPTION
**Pull request by nblackburn**
Removed unnecessary semi-colons.

### CODE REVIEW

**Comment by afshinm** [comment]
as far as I remember, we need these semicolons for some of minifying tasks?

**Comment by nblackburn** [comment]
@afshinm JSHint suggests that they need not be there.

**Comment by afshinm** [comment]
Ok. Could you please try to run the minify task and test the minified JS (without these semicolons)?

**Comment by afshinm** [comment]
Btw, thanks for your contribution.

**Comment by nblackburn** [comment]
@afshinm Absolutely no problem, thanks for creating the library.

**Comment by afshinm** [comment]
Yeah sure, just want to make sure this change won't break anything.

**Comment by afshinm** [comment]
any updates on this?

**Comment by nblackburn** [comment]
Sorry, i have been a little busy. I have run some quick tests on non-minified and minified sources and both run fine.

**Comment by afshinm** [comment]
thanks!

**Pull request merged**
