### PR TITLE
bottom should stay on bottom even when the tooltipLayer changes size

### PR DESCRIPTION
**Pull request by jayenashar**
(like when a font loads)

### CODE REVIEW

**Comment by afshinm** [comment]
Can you please give me a demo?

**Comment by jayenashar** [comment]
you want me to add a demo to the repo, or send you a link to where i use it?
http://suburbchooser.com/homechooser/beta/

**Comment by afshinm** [comment]
Can you please update this PR with upstream? I can't merge it automatically.

**Comment by kleinph** [comment]
By the way, here is a demo for this issue http://jsfiddle.net/kkw1rddd/1/

**Comment by jayenashar** [comment]
@afshinm I have updated the PR with upstream.

@kleinph I have only fixed the issue for 'bottom'.  Here is a demo: http://jsfiddle.net/kkw1rddd/2/
Would you like me to look at fixing the other positions?

**Comment by afshinm** [comment]
@jayenashar i think we have this issue for other positions. Can you please address the issue for other positions?

**Comment by jayenashar** [comment]
@afshinm i fixed up top.  left & right look ok.  i'm not sure how to fix floating without breaking support for IE8.

**Comment by afshinm** [comment]
Awesome @jayenashar. Thank you.

**Pull request merged**
