### PR TITLE
Added the option to simulate a click when the user go to a step

### PR DESCRIPTION
**Pull request by Angelmmiguel**
For example, I added a click simulation on steps where the element is an anchor. It's interesting when you want to show what happens when click on a button (open a menu...). Added the documentation and an example.

### CODE REVIEW

**Comment by JeansReal** [comment]
This is going to be supported?

**Comment by Angelmmiguel** [comment]
I don't think so @JeansReal. I created this PR two years ago...

**Comment by afshinm** [comment]
Apologies for this delay @Angelmmiguel.

Could you please rebase it? I'm going to merge it for the next version.

**Comment by Angelmmiguel** [comment]
Np @afshinm :)

I must refork the project and create a new PR because I removed the old fork. Also, the code changed since I created this PR so I need to check it again. Please, don't close this PR until I create the new one.

**Comment by Angelmmiguel** [comment]
Hello @m4knV,

Thank you for approving the PR. However, the last time I tried it, it didn't work with the latest changes of the library. I didn't find a fast solution and I didn't have too much time, so I couldn't fix it. 

If you updated the library and it works now, it's perfect! I just wanted to confirm with you that this feature works properly.

**Comment by hajimurtaza** [comment]
Will this be approved , its a great funtionality to have @bozdoz @afshinm

**Comment by bozdoz** [comment]
I don't see this happening, unless someone has the time to fix the conflicts and show what it does.

**Pull request closed without merging**
